---
Buttons: ["Apply","Alaki","Cancel"]
Controls:
  item1:
    class: "label"
    x: 0
    y: 0
    width: 1
    height: 1
    label: "This is not a label?!"
  item2:
    class: "edit"
    x: 1
    y: 0
    width: 1
    height: 1
    hint: ""
    text: ""
  item3:
    class: "intedit"
    x: 2
    y: 0
    width: 1
    height: 1
    hint: ""
    value: 26
    min: nil
    max: nil
  item4:
    class: "floatedit"
    x: 3
    y: 0
    width: 1
    height: 1
    hint: ""
    value: 37.42
    min: 30
    max: 40
    step: .2
  item5:
    class: "textbox"
    x: 4
    y: 0
    width: 1
    height: 1
    hint: ""
    text: ""
  item6:
    class: "dropdown"
    x: 0
    y: 1
    width: 1
    height: 1
    hint: ""
    items: ["item1", "item2", "item3", "item4"]
    value: "item2"
  item7:
    class: "checkbox"
    x: 1
    y: 1
    width: 1
    height: 1
    hint: ""
    label: "This is a checkbox"
    value: false
  item8:
    class: "color"
    x: 2
    y: 1
    width: 1
    height: 1
    hint: ""
    value: "#F0EA82"
  item9:
    class: "coloralpha"
    x: 3
    y: 1
    width: 1
    height: 1
    hint: ""
    value: "#234567"
  item10:
    class:  "alpha"
    x: 4
    y: 1
    width: 1
    height: 1
    hint: ""
    value: "#AA"